### ISSUE TITLE
Alain Has No Personality

### ISSUE THREAD

**Issue by jonirons** [sergile/alain#2]
This can be fixed with a simple image.
![pumpkalain](https://cloud.githubusercontent.com/assets/14964819/10855901/9b14b024-7f1a-11e5-8c20-4b994e4932fb.jpg)

**Comment by nexdrew** [comment]
<img width="116" alt="appearin-profile" src="https://cloud.githubusercontent.com/assets/1929625/11040491/8985c6f0-86da-11e5-9459-05ea09f1e81a.png">
